<!-- #AREA -->
<section id="AREA" class="bg-yellow">
  <div class="container">
    <p class="sub-title bg-white text-center mb-4">すぐに駆けつけます！</p>
    <h3 class="title text-center mb-4 px-0">対応エリア</h3>
    <h4 class="text-center fs-2 fw-bold mb-3">東京都</h4>
    <ul class="area-box d-flex list-unstyled flex-wrap gap-3 bg-white mb-4">
      <li>足立区</li>
      <li>荒川区</li>
      <li>板橋区</li>
      <li>江戸川区</li>
      <li>大田区</li>
      <li>葛飾区</li>
      <li>北区</li>
      <li>江東区</li>
      <li>品川区</li>
      <li>渋谷区</li>
      <li>新宿区</li>
      <li>杉並区</li>
      <li>墨田区</li>
      <li>世田谷区</li>
      <li>台東区</li>
      <li>中央区</li>
      <li>千代田区</li>
      <li>豊島区</li>
      <li>中野区</li>
      <li>練馬区</li>
      <li>文京区</li>
      <li>港区</li>
      <li>目黒区</li>
      <li>昭島市</li>
      <li>稲城市</li>
      <li>清瀬市</li>
      <li>国立市</li>
      <li>小金井市</li>
      <li>国分寺市小平市</li>
      <li>狛江市</li>
      <li>立川市</li>
      <li>多摩市</li>
      <li>調布市</li>
      <li>西東京市</li>
      <li>八王子市</li>
      <li>東久留米市</li>
      <li>東村山市</li>
      <li>東大和市</li>
      <li>日野市</li>
      <li>府中市</li>
      <li>町田市</li>
      <li>三鷹市</li>
      <li>武蔵野市</li>
      <li>武蔵村山市</li>
    </ul>
    <h4 class="text-center fs-2 fw-bold mb-3">神奈川県</h4>
    <ul class="area-box d-flex list-unstyled flex-wrap gap-3 bg-white mb-4">
    <li>川崎市麻生区</li>
      <li>川崎市川崎区</li>
      <li>川崎市幸区</li>
      <li>川崎市高津区</li>
      <li>川崎市多摩区</li>
      <li>川崎市中原区</li>
      <li>川崎市宮前区</li>
      <li>横浜市青葉区</li>
      <li>横浜市旭区</li>
      <li>横浜市緑区</li>
      <li>横浜市泉区</li>
      <li>横浜市磯子区</li>
      <li>横浜市神奈川区</li>
      <li>横浜市金沢区</li>
      <li>横浜市南区</li>
      <li>横浜市港北区</li>
      <li>横浜市栄区</li>
      <li>横浜市瀬谷区横浜市都筑区</li>
      <li>横浜市鶴見区</li>
      <li>横浜市戸塚区</li>
      <li>横浜市中区</li>
      <li>横浜市港南区</li>
      <li>横浜市西区</li>
      <li>横浜市保土ヶ谷区</li>
      <li>相模原市緑区</li>
      <li>相模原市中央区</li>
      <li>相模原市南区</li>
      <li>藤沢市</li>
      <li>鎌倉市</li>
      <li>厚木市</li>
      <li>座間市</li>
      <li>海老名市</li>
      <li>大和市</li>
      <li>横須賀市</li>
      <li>逗子市</li>
      <li>葉山町</li>
      <li>綾瀬市</li>
      <li>茅ヶ崎市</li>
      <li>寒川町</li>
      <li>平塚市</li>
      <li>伊勢原市</li>
    </ul>
    <h4 class="text-center fs-2 fw-bold mb-3">千葉県</h4>
    <ul class="area-box d-flex list-unstyled flex-wrap gap-3 bg-white mb-4">
      <li>千葉市稲毛区</li>
      <li>千葉市中央区</li>
      <li>千葉市花見川区</li>
      <li>千葉市美浜区</li>
      <li>千葉市緑区</li>
      <li>千葉市若葉区</li>
      <li>市川市</li>
      <li>浦安市</li>
      <li>柏市<li>習志野市</li>
      <li>船橋市</li>
      <li>松戸市</li>
      <li>流山市</li>
      <li>鎌ヶ谷市</li>
      <li>八千代市</li>
      <li>四街道市</li>
      <li>白井市</li>
      <li>我孫子市</li>
      <li>野田市</li>
      <li>木更津市</li>
      <li>袖ヶ浦市</li>
      <li>君津市</li>
      <li>富津市</li>
      <li>市原市</li>
    </ul>
    <h3 class="text-center fs-2 fw-bold mb-3">埼玉県</h3>
    <ul class="area-box d-flex list-unstyled flex-wrap gap-3 bg-white mb-4">
      <li>さいたま市岩槻区</li>
      <li>さいたま市浦和区</li>
      <li>さいたま市大宮区</li>
      <li>さいたま市北区</li>
      <li>さいたま市桜区</li>
      <li>さいたま市中央区</li>
      <li>さいたま市西区</li>
      <li>さいたま市緑区</li>
      <li>さいたま市南区</li>
      <li>さいたま市見沼区</li>
      <li>川口市</li>
      <li>越谷市</li>
      <li>草加市</li>
      <li>新座市</li>
      <li>朝霞市<li>三郷市</li>
      <li>戸田市</li>
      <li>富士見市</li>
      <li>和光市</li>
      <li>蕨市</li>
      <li>八潮市</li>
      <li>志木市</li>
      <li>所沢市</li>
      <li>川越市</li>
      <li>春日部市</li>
      <li>吉川市</li>
      <li>三芳町</li>
      <li>ふじみ野市</li>
      <li>松伏町</li>
      <li>杉戸町</li>
      <li>宮代町</li>
      <li>白岡市</li>
      <li>蓮田市</li>
      <li>伊奈町</li>
    </ul>
  </div>
</section>